'use client'
import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import { SessionProvider } from "./_components/SessionProvider";
import { Toaster } from 'react-hot-toast'

const outfit=Outfit({subsets:["latin"]});
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


import { PrismaClient } from '@prisma/client'
import { useEffect, useState } from "react";
import { usePathname } from "next/navigation";
import { UpdateCartContext } from "./_context/UpdateCartContext";
import { PayPalScriptProvider } from "@paypal/react-paypal-js";

const prisma = new PrismaClient()

export  default  function RootLayout({ children }) {
    // const categoryList = await prisma.category.findMany();
 const [categoryList, setCategoryList] = useState([]);

     useEffect(() => {
    const fetchCategories = async () => {
      try {
        const res = await fetch('/api/getCategoryList');
        if (!res.ok) throw new Error('Failed to fetch categories');
        const data = await res.json();
        setCategoryList(data);
      } catch (err) {
       console.log("error is",err);
      } 
    };

    fetchCategories();
  }, []);

const params=usePathname();
const showHeader=params=='/login' || params=='/register'?false:true;
const [updateCart,setUpdateCart]=useState(false);

  return (


    <html lang="en">
      <body
        className={outfit.className}
      >
      <UpdateCartContext.Provider value={{updateCart,setUpdateCart}}>

       <SessionProvider>
       {showHeader &&  <Header categoryList={categoryList}/>}
        {children}
        <Toaster />
    
       </SessionProvider>

       </UpdateCartContext.Provider>
        </body>
    </html>
  
  );
}
